### ISSUE TITLE
Typo in file path on packagecloud

### ISSUE THREAD

**Issue by jryburn** [kentik/kprobe#9]
On packagecloud in the Debian packages there appears to be a typo in the path for the files.

sr/share/doc/kprobe/copyright -> /usr/share/doc/kprobe/copyright
sr/bin/kprobe -> /usr/bin/kprobe

![Screen Shot 2020-04-28 at 12 31 23 PM](https://user-images.githubusercontent.com/12754737/80518693-70ba5180-894c-11ea-81cf-52ac45babf23.png)

**Comment by kentik-will** [comment]
Think this is just an issue with the packagecloud UI
